services:
  db:
    container_name: MySQL
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: chimy-db:latest
    tty: true  
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chimyapp
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    

  backend:
    container_name: go-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/api
    ports:
      - "8080:8080" 
    tty: true
    env_file:
      - ./mysql/.env 
    depends_on:
      - db  
    networks:
      - api_test_network


  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    networks:
      - api_test_network

volumes:
  mysql_test_volume:
    name: mysql_test_volume


networks:
  api_test_network:
    external: true
