services:
  db:
    container_name: mysql
    build:
      context: .
      dockerfile: Docker/MySQL/Dockerfile
    image: chimy-db:latest
    tty: true  
    platform: linux/x86_64
    ports:
      - 3307:3306
    env_file:
      - ./Docker/MySQL/.env
    volumes:
      - type: volume
        source: mysql_data
        target: /var/lib/mysql
      
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d  

    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    

  backend:
    container_name: go-api
    build:
      context: .
      dockerfile: Docker/Go/Dockerfile
    volumes:
      - ./api:/api
    ports:
      - "8080:8080" 
    tty: true
    env_file:
      - ./Docker/MySQL/.env 
    # command: reflex - '\.go$$' -s -- sh -c 'go run cmd/main.go'  
    depends_on:
      - db  
    # networks:
    #   - api_test_network


  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Docker/NextJS/Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    # networks:
    #   - api_test_network

volumes:
  mysql_data:

# networks:
#   api_test_network:
#     external: true
